### ISSUE TITLE
Download version / proxy issues

### ISSUE THREAD

**Issue by docunext** [nwjs/npm-installer#29] opened 2015-10-09 16:21 UTC
Hi,

The download npm package that npm-installer uses is currently ^3.3.0. That version uses its own proxy detection:

https://github.com/kevva/download/blob/v3.3.0/index.js#L33

The current version of download, 4.1.2, uses caw and get-proxy to detect proxy settings; they are different:

https://github.com/kevva/get-proxy/blob/master/index.js#L6

For me, this is an issue as I have a default proxy in my .npmrc and often override it via the command line. Upgrading to 4.1.2 allows me to at least use an environment variable to override the value in my .npmrc. There is a separate issue that I believe get-proxy should detect proxies set as command line arguments, but I'll submit an issue in that project.

Thanks!

Albert

**Comment by Mithgol** [comment] 2016-02-26 14:58
Would it be enough to upgrade the required version of out `download` dependency?

What would be that changes to the latest (i.e. proxy-related) section of our README?

**Comment by Mithgol** [comment] 2016-05-04 12:57
Starting from the version `nw@0.15.0-beta2sdk-2` (from d926efd44c31ae19feab0b0cac6a02c95712b94f onwards) this package uses `download@4.4.3` as its dependency.

P. S.   Sorry for the late upgrade, I've been a bit busy.

P. P. S.   We still need some changes in README before it becomes okay to close this issue.

**Comment by amaslenn** [comment] 2017-02-14 10:36
Hi @Mithgol!
I have an issue with proxy. I use `v0.20.2` on Windows and macOS. If I set both `http_proxy` and `https_proxy` (both correct and deffer by protocol and port, other apps and `npm` itself works fine with them), post install scripts fails with `tunneling socket could not be established, cause=socket hang up`. With `https_proxy=''` script works fine.

**Comment by Mithgol** [comment] 2017-02-16 14:51
Hi @amaslenn!

Does kevva/download#64 seem like the issue that you've encountered?

**Comment by amaslenn** [comment] 2017-02-16 18:47
@Mithgol yes, it looks similar. Except exact `cause`: I get `hang up`, other reasons are mentioned in the issue. But root cause could be the same.

**Comment by Mithgol** [comment] 2017-02-23 21:04
@amaslenn I am inclined to decide to wait until the cause is fixed by the authors of `download` unless you suggest a good enough replacement for `download` (where “good enough” means “won't introduce more problems than it solves”).

**Comment by amaslenn** [comment] 2017-02-24 11:02
@Mithgol sounds good. You can ping me to verify fix.

**Comment by Mithgol** [comment] 2017-07-12 18:21
Two hours ago I merged @nurishi's b9737cf23bcfe2fa7f2a904d7524756c52a590fc.

We are now using `download@^5.0.3`, which uses `caw@^2.0.0`, which uses `get-proxy@^1.0.1`, which has [some code](https://github.com/kevva/get-proxy/blob/master/index.js) to ensure that `http_proxy` and `https_proxy` both work.

Does it really help? Please try `nw@0.23.6-1` or `nw@0.23.6-sdk-1` to verify the fix.

**Comment by amaslenn** [comment] 2017-07-17 06:52
I'm afraid I don't have required machine configuration now to verify it.
Let's assume it works.

**Comment by Mithgol** [comment] 2017-07-17 13:39
Okay, let's do it.

I am closing this issue (considering it fixed).

If a proxy-related issue surfaces in the future, it should be (by default) treated as a separate issue (until proven otherwise) and opened as a new issue on GitHub.

**Closed by Mithgol** 2017-07-17 13:39 UTC
