### ISSUE TITLE
 about sound app fail node web kit 32 play it with windows 64

### ISSUE THREAD

**Issue by tayson2000** [nwjs/npm-installer#51] opened 2016-10-19 21:11 UTC
I hope somebody can help me, I make a simple application and bag it with node webkit, I did it with node web kit 32- bit v0.3.7 in my windows operating system 64, the application ran but did not sound, then I returned to create it with  node web kit 64-bit v0.12.3 and play it with sound in my windows 64, my question is that then the sounds with node web kit 32 bit does not run well on an windows operating system 64,  i should create to windows 32 with nodeweb kit 32-bit and to windows 64 with the node web kit 64, Thank you?

**Comment by Mithgol** [comment] 2016-10-22 22:10
NW.js 32-bit for Windows should run on Windows 64-bit as well as on Windows 32-bit, but that does not work the other way (NW.js 64-bit would have problems on Windows 32-bit).

The sound-related problem is, most likely, not caused by NW's npm installer (discussed here); therefore you'd better report your issue to https://github.com/nwjs/nw.js/issues (the main collection of NW.js issues) instead.

In addition to that you may try getting some help in the NW.js-related [Google Group](https://groups.google.com/d/forum/nwjs-general) or [Gitter](https://gitter.im/nwjs/nw.js) chat.

I also notice that the newest NW.js version is currently v0.18.2, and thus you might try upgrading to that version from your v0.12.3 and see if it helps.

I am going to close this issue because it does not look like it's installer-related.

**Closed by Mithgol** 2016-10-22 22:10 UTC
