### ISSUE TITLE
Install nw@0.20.0 fails on OSX Sierra

### ISSUE THREAD

**Issue by vuphuctho** [nwjs/npm-installer#53] opened 2017-01-31 15:25 UTC
Installing nw with command `npm install nw` hanged at `node scripts/install.js` for around 1 hour, and returned following error message log:

```
> node scripts/install.js

end of central directory record signature not found
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "nw"
npm ERR! node v6.9.4
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! nw@0.20.0 postinstall: `node scripts/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the nw@0.20.0 postinstall script 'node scripts/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the nw package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node scripts/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs nw
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls nw
npm ERR! There is likely additional logging output above.
```

There is no proxy set up in my machine, so it's unlikely network problem.

**Comment by shama** [comment] 2017-01-31 17:18
Closing as duplicate of #42

**Closed by shama** 2017-01-31 17:18 UTC
